.TH LOGKSI-INTEGRATE 1
.\"
.SH NAME
\fBlogksi integrate \fR- Integrate the log blocks and their signatures into log signatures file.
.\"
.SH SYNOPSIS
.HP 4
\fBlogksi integrate \fIlogfile \fR[\fB-o \fIoutput.logsig\fR]
.\"
.SH DESCRIPTION
Integrates the temporary log blocks file and log signatures file containing the respective KSI signatures into one final log signature file.
.LP
If \fIlogfile\fR is given as input parameter, the respective temporary files (\fIblocks.dat\fR and \fIblock-signatures.dat\fR) to create the final log signature file are expected to locate in the folder \fIlogfile.logsig.parts\fR. These files are created during logging and the integration can be performed after the logging has rotated.
.LP
If no output file name is specified, a dedicated \fIlogfile.logsig\fR file is generated next to the original \fIlogfile\fR.
.LP
For integration to succeed, two criteria need to be met:
.LP
.IP \(bu 4
The order of log blocks in \fIblocks.dat\fR and signatures in \fIblock-signatures.dat\fR needs to match.
.IP \(bu 4
The root hash of each block in the blocks file needs to be equal to the one in the signatures file.
.LP
.\"
.SH OPTIONS
.TP
\fB-o \fIlogfile.logsig\fR
Specify the output file path for the log signature file. If not specified, the log signature file is saved as \fIlogfile.logsig\fR in the same folder where the \fIlogfile\fR is located. If the output file name is explicitly specified, existing file is always overwritten.
.br
.\"
.SH EXIT STATUS
See \fBlogksi\fR(1) for more information.
.\"
.SH EXAMPLES
.TP 2
\fB1
\fRTo integrate temporary files \fI/var/log/secure.logsig.parts/blocks.dat\fR and \fI/var/log/secure.logsig.parts/block-signatures.dat\fR into complete log signature file with default name \fI/var/log/secure.logsig\fR:
.LP
.RS 4
\fBlogksi integrate -i \fI/var/log/secure
.RE
.\"
.SH AUTHOR
Guardtime AS, http://www.guardtime.com/
.LP
.\"
.SH SEE ALSO
\fBlogksi\fR(1), \fBlogksi-sign\fR(1), \fBlogksi-extend\fR,(1) \fBlogksi-verify\fR(1), \fBlogksi-conf\fR(5)
