.TH LOGKSI-SIGN 1
.\"
.SH NAME
\fBlogksi sign \fR- Sign unsigned blocks for the given log file.
.\"
.SH SYNOPSIS
.HP 4
\fBlogksi sign \fR[\fIlogfile\fR] [\fB-o \fIout.logsig\fR] \fB-S \fIURL \fR[\fB--aggr-user \fIuser \fB--aggr-key \fIkey\fR] [\fImore options\fR]
.\"
.SH DESCRIPTION
Signs the unsigned log blocks in a log signature file of a given \fIlogfile\fR. The name of the log signature file is expected to be \fIlogfile.logsig\fR. If no \fIlogfile\fR is given, input is read from \fIstdin\fR and should correspond to a log signature file.
.LP
\fBlogksi sign\fR provides the recovery signing functionality for cases when some log blocks have been left unsigned during routine signing/logging. For instance, when the KSI service was not reachable.
.LP
User must have access to KSI signing service (KSI Aggregator) for signing.
.\"
.SH OPTIONS
.TP
\fB-o \fIout.logsig\fR
Specify the name of the output log signature file. If not specified, the input file \fIlogfile.logsig\fR is modified. The backup of the original log signature file will be saved to \fIlogfile.logsig.bak\fR. If the output file name is explicitly specified, an existing file will always be overwritten and no backup file will be created. Use '-' as file name to redirect the output as a binary stream to \fIstdout\fR.
.\"
.TP
\fB-S \fIURL\fR
Specify the signing service (KSI Aggregator) URL.
.\"
.TP
\fB--aggr-user \fIuser\fR
Specify the username for signing service.
.\"
.TP
\fB--aggr-key \fIkey\fR
Specify the HMAC key for signing service.
.\"
.TP
\fB--aggr-hmac-alg \fIalg\fR
Hash algorithm to be used for computing HMAC on outgoing messages towards KSI aggregator. If not set, default algorithm is used. Use \fBksi -h \fRto get the list of supported hash algorithms.
.\"
.TP
\fB-d\fR
Print detailed information about processes and errors to \fIstderr\fR.
.\"
.TP
\fB--show-progress\fR
Print signing progress. Only valid with -d\fR.
.\"
.TP
\fB--conf \fIfile\fR
Read configuration options from the given file. It must be noted that configuration options given explicitly on command line will override the ones in the configuration file. See \fBlogksi-conf\fR(5) for more information.
.\"
.TP
\fB--log \fIfile\fR
Write libksi log to the given file. Use '-' as file name to redirect the log to \fIstdout\fR.
.br
.\"
.SH EXIT STATUS
See \fBlogksi\fR(1) for more information.
.\"
.SH EXAMPLES
In the following examples it is assumed that KSI service configuration options (URLs, access credentials) are defined. See \fBlogksi-conf\fR(5) for more information.
.\"
.TP 2
\fB1
To sign unsigned blocks in log signature file \fI/var/log/secure.logsig\fR and save the amended log signature file in \fI/var/log/secure-signed.logsig\fR:
.LP
.RS 4
\fBlogksi sign \fI/var/log/secure\fR \fB-o \fI/var/log/secure-signed.logsig\fR
.RE
.\"
.TP 2
\fB2
To sign unsigned blocks in log signature file \fI/var/log/secure.logsig\fR and save the result in the same file after creating the respective backup file \fI/var/log/secure.logsig.bak\fR:
.LP
.RS 4
\fBlogksi sign \fI/var/log/secure\fR
.RE
.\"
.SH ENVIRONMENT
Use the environment variable \fBKSI_CONF\fR to define the default configuration file. See \fBlogksi-conf\fR(5) for more information.
.LP
.SH AUTHOR
Guardtime AS, http://www.guardtime.com/
.LP
.SH SEE ALSO
\fBlogksi\fR(1), \fBlogksi-extend\fR(1), \fBlogksi-integrate\fR(1), \fBlogksi-verify\fR(1), \fBlogksi-conf\fR(5)
