.TH LOGKSI-EXTEND 1
.\"
.SH NAME
\fBlogksi extend \fR- Extend KSI signatures in log signature file.
.\"
.SH SYNOPSIS
.HP 4
\fBlogksi extend \fR[\fIlogfile\fR] [\fB-o \fIout.logsig\fR] \fB-X \fIURL \fR[\fB--ext-user \fIuser \fB--ext-key \fIkey\fR] \fB-P \fIURL \fR[\fB--cnstr \fIoid\fR=\fIvalue\fR]... [\fImore_options\fR]
.HP 4
\fBlogksi extend \fR[\fIlogfile\fR] [\fB-o \fIout.logsig\fR] \fB-X \fIURL \fR[\fB--ext-user \fIuser \fB--ext-key \fIkey\fR] \fB-P \fIURL \fR[\fB--cnstr \fIoid\fR=\fIvalue\fR]... \fB--pub-str \fIstr \fR[\fImore_options\fR]
.HP 4
\fBlogksi extend \fR[\fIlogfile\fR] [\fB-o \fIout.logsig\fR] \fB--conf \fIlogksi.conf\fR [\fImore_options\fR]
.\"
.SH DESCRIPTION
Finds the log signature file (\fIlogfile.logsig\fR) based on the specified log file \fIlogfile\fR and extends KSI signatures in it to the desired publication. If no \fIlogfile\fR is specified, the input is expected from \fIstdin\fR and correspond to a log signature file.
.LP
After the signatures are extended and the corresponding publication records are attached, the log signatures can be verified using publication-based verification where only trusted publications file or a publication string in printed media is needed to perform the verification. See \fBlogksi-verify\fR(1) for details.
.LP
User must have access to KSI extending service and trusted KSI publications file. By default the KSI signatures are extended to the earliest available publication. Use the option \fB--pub-str\fR to extend signatures to the publication denoted by the given publication string.
.LP
Note that all KSI signatures present in the log signature file will be attempted to extend to the same publication. If for some reason the extending of at least one signature fails, none of the signatures are extended.
.LP
If both, input and output files are left unspecified, the \fIstdin\fR and \fIstdout\fR are used, respectively.
.\"
.SH OPTIONS
.TP
\fB-o \fIout.logsig\fR
Specify the output file path for the extended log signature file. If not specified, the input file \fIlogfile.logsig\fR is modified. The backup of the original log signature file will be saved to \fIlogfile.logsig.bak\fR. If extending fails, the newly created \fIlogfile.logsig\fR will be deleted and the original \fIlogfile.logsig\fR will be restored from the backup file. If output file name is explicitly specified, the existing file will always be overwritten and no backup file will be created. Use '-' as file name to redirect the output as binary stream to \fIstdout\fR.
.\"
.TP
\fB-X \fIURL\fR
Specify the extending service (KSI Extender) URL.
.\"
.TP
\fB--ext-user \fIuser\fR
Specify the username for extending service.
.\"
.TP
\fB--ext-key \fIkey\fR
Specify the HMAC key for extending service.
.\"
.TP
\fB-P \fIURL\fR
Specify the publications file URL (or file with URI scheme 'file://').
.\"
.TP
\fB--cnstr \fIoid\fR=\fIvalue\fR
Specify the OID of the PKI certificate field (e.g. e-mail address) and the expected value to qualify the certificate for verification of publications file's PKI signature. At least one constraint must be defined. All values from lower priority source are ignored (see \fBlogksi-conf\fR(5)).
.RS
.HP 0
For more common OIDs there are convenience names defined:
.IP \(bu 4
\fBE\fR or \fBemail\fR for OID 1.2.840.113549.1.9.1
.IP \(bu 4
\fBCN\fR or \fBcname\fR for OID 2.5.4.3
.IP \(bu 4
\fBC or \fBcountry\fR for OID 2.5.4.6
.IP \(bu 4
\fBO\fR or \fBorg\fR for OID 2.5.4.10
.RE
.\"
.TP
\fB--pub-str \fIstr\fR
Specify the publication record as publication string to extend the signatures to.
.\"
.TP
\fB-V \fIfile\fR
Specify the certificate file in PEM format for publications file verification. All values from lower priority source are ignored (see \fBlogksi-conf\fR(5)).
.\"
.TP
\fB-d\fR
Print detailed information about processes and errors to \fIstderr\fR.
.\"
.TP
\fB--conf \fIfile\fR
Read configuration options from given file. It must be noted that configuration options given explicitly on command line will override the ones in the configuration file. See \fBlogksi-conf\fR(5) for more information.
.\"
.TP
\fB--log \fIfile\fR
Write \fIlibksi\fR log to given file. Use '-' as file name to redirect log to \fIstdout\fR.
.br
.\"
.SH EXIT STATUS
See \fBlogksi\fR(1) for more information.
.\"
.SH EXAMPLES
In the following examples it is assumed that KSI service configuration options (URLs, access credentials) are defined. See \fBlogksi-conf\fR(5) for more information.
.\"
.TP 2
\fB1
\fRTo extend the signatures in \fI/var/log/secure.logsig\fR to the earliest available publication and save the file as \fI/var/log/secureExt.logsig\fR:
.LP
.RS 4
\fBlogksi extend \fI/var/log/secure \fB-o \fI/var/log/secureExt.logsig
.RE
.\"
.TP 2
\fB2
\fRTo extend the signatures in \fI/var/log/secure.logsig\fR to the specified publication (the publication string available from Financial Times, ISSN: 0307-1766, 2016-03-17 given as example) and save the result with default name \fI/var/log/secure.logsig\fR:
.LP
.RS 4
\fBlogksi extend \fI/var/log/secure \fB--pub-str \fIAAAAAA-CW45II-AAKWRK-F7FBNM-KB6FNV-DYYFW7-PJQN6F-JKZWBQ-3OQYZO-HCB7RA-YNYAGA-ODRL2V
.RE
.\"
.SH ENVIRONMENT
Use the environment variable \fBKSI_CONF\fR to define the default configuration file. See \fBlogksi-conf\fR(5) for more information.
.LP
.\"
.SH AUTHOR
Guardtime AS, http://www.guardtime.com/
.LP
.\"
.SH SEE ALSO
\fBlogksi\fR(1), \fBlogksi-sign\fR(1), \fBlogksi-integrate\fR(1), \fBlogksi-verify\fR(1), \fBlogksi-conf\fR(5)
