.TH LOGKSI-INTEGRATE 1
.\"
.SH NAME
\fBlogksi integrate \fR- Integrate the log signature blocks file and respective KSI signatures file into final log signature file.
.\"
.SH SYNOPSIS
.HP 4
\fBlogksi integrate \fIlogfile \fR[\fB-o \fIoutput.logsig\fR]
.\"
.SH DESCRIPTION
Integrates the two temporary files created while logging into the \fIlogfile\fR:
.LP
.IP \(bu 4
the log signatures blocks file: \fIlogfile.logsig.parts/blocks.dat\fR; and
.IP \(bu 4
the log signature file containing the respective KSI signatures: \fIlogfile.logsig.parts/block-signatures.dat\fR.
.LP
If no output file name is specified, a dedicated \fIlogfile.logsig\fR file is generated next to the original \fIlogfile\fR.
.LP
The integration of these files can be performed after the logging has rotated.
.LP
For integration to succeed, two criteria need to be met:
.LP
.IP \(bu 4
The order of log blocks in \fIblocks.dat\fR and KSI signatures in \fIblock-signatures.dat\fR needs to match.
.IP \(bu 4
The root hash of each block in the log signatures blocks file needs to be equal to the one in the KSI signatures file.
.LP
If some KSI signatures are missing from the log signature file \fIblock-signatures.dat\fR, respective \fIno-sig\fR field is recognised and integration is performed anyway. The missing signatures can then be acquired using \fBlogksi sign\fR function.
.\"
.SH OPTIONS
.TP
\fB-o \fIlogfile.logsig\fR
Specify the output file path for the log signature file. If not specified, the log signature file is saved as \fIlogfile.logsig\fR in the same folder where the \fIlogfile\fR is located. Any existing files with output file name will be overwritten.
.br
.\"
.SH EXIT STATUS
See \fBlogksi\fR(1) for more information.
.\"
.SH EXAMPLES
.TP 2
\fB1
\fRTo integrate temporary files \fI/var/log/secure.logsig.parts/blocks.dat\fR and \fI/var/log/secure.logsig.parts/block-signatures.dat\fR into complete log signature file with default name \fI/var/log/secure.logsig\fR:
.LP
.RS 4
\fBlogksi integrate \fI/var/log/secure
.RE
.\"
.SH AUTHOR
Guardtime AS, http://www.guardtime.com/
.LP
.\"
.SH SEE ALSO
\fBlogksi\fR(1), \fBlogksi-sign\fR(1), \fBlogksi-extend\fR,(1) \fBlogksi-verify\fR(1), \fBlogksi-conf\fR(5)
