.TH LOGKSI-INTEGRATE 1
.\"
.SH NAME
\fBlogksi integrate \fR- Integrate the log signature blocks file and respective KSI signatures file into a final log signature file.
.\"
.SH SYNOPSIS
.HP 4
\fBlogksi integrate \fIlogfile \fR[\fB-o \fIout.logsig\fR]
.\"
.SH DESCRIPTION
Integrates the two temporary files created while asynchronously signing the log file \fIlogfile\fR:
.LP
.IP \(bu 4
the log signature blocks file: \fIlogfile.logsig.parts/blocks.dat\fR; and
.IP \(bu 4
the log signature file containing the respective KSI signatures: \fIlogfile.logsig.parts/block-signatures.dat\fR.
.LP
If the output file name is not specified, it is derived from the name of the log file \fIlogfile\fR by adding the standard suffix \fI.logsig\fR. An attempt to overwrite an existing log signature file will result in an error.
.LP
The integration of the files can be performed once both files are complete. \fBlogksi integrate \fR waits to acquire a read lock on the files before integrating them. The read lock is advisory and relies on the same implementation in the signing application.
.LP
If the temporary files do not exist, but a matching log signature exists, it is assumed that the log signature is the output of a synchronous signing process. \fBlogksi integrate \fR waits to acquire a read lock on the log signature file and then skips the actual integration. The read lock is advisory and relies on the same implementation in the signing application.
.LP
During integration the following is checked:
.LP
.IP \(bu 4
The order of log blocks in \fIblocks.dat\fR and KSI signatures in \fIblock-signatures.dat\fR needs to match.
.IP \(bu 4
The root hash of each block in the log signature blocks file needs to be equal to the one in the KSI signatures file.
.LP
If some KSI signatures are missing from the log signature file \fIblock-signatures.dat\fR, a respective \fIno-sig\fR field is recognised and integration is performed anyway. The missing signatures can then be acquired using \fBlogksi sign\fR function.
.\"
.SH OPTIONS
.TP
\fB-o \fIout.logsig\fR
Specify the name of the integrated output log signature file. If not specified, the log signature file is saved as \fIlogfile.logsig\fR in the same folder where the \fIlogfile\fR is located. An attempt to overwrite an existing log signature file will result in an error.
.\"
.TP
\fB-d\fR
Print detailed information about processes and errors to \fIstderr\fR.
.\"
.TP
\fB--log \fIfile\fR
Write \fIlibksi\fR log to the given file. Use '-' as file name to redirect the log to \fIstdout\fR.
.br
.\"
.SH EXIT STATUS
See \fBlogksi\fR(1) for more information.
.\"
.SH EXAMPLES
.TP 2
\fB1
\fRTo integrate temporary files \fI/var/log/secure.logsig.parts/blocks.dat\fR and \fI/var/log/secure.logsig.parts/block-signatures.dat\fR into a complete log signature file with the default name \fI/var/log/secure.logsig\fR:
.LP
.RS 4
\fBlogksi integrate \fI/var/log/secure
.RE
.\"
.SH AUTHOR
Guardtime AS, http://www.guardtime.com/
.LP
.\"
.SH SEE ALSO
\fBlogksi\fR(1), \fBlogksi-extend\fR(1), \fBlogksi-extract\fR(1), \fBlogksi-sign\fR(1), \fBlogksi-verify\fR(1), \fBlogksi-conf\fR(5)
